services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: gridee
      POSTGRES_USER: gridee_user
      POSTGRES_PASSWORD: gridee_pass
    ports:
      - "5433:5432"
  redis:
    image: redis:7
    ports:
      - "6379:6379"
