/**
 * src/templates/index.ts
 *
 * Gridee WhatsApp / SMS message template module.
 *
 * Rules:
 *  - Every function is a pure function: no imports, no side effects, no I/O.
 *  - WhatsApp text formatting: *bold*, _italic_, line breaks via \n.
 *  - Tone: warm, friendly, Nigerian — not a banking robot.
 *  - Every message must stay under 4,096 characters (WhatsApp hard limit).
 *
 * Ownership : Mark David  (copy, tone, formatting)
 * Consumed by: notificationService.ts -> WhatsApp sender / SMS fallback
 */

/**
 * Sent immediately after a user completes registration.
 * Role-aware: landlords and tenants receive different first-step guidance.
 *
 * @param name - The user's full name as entered during registration.
 * @param role - The user's role on the platform.
 */
export function welcomeMessage(
  name: string,
  role: "landlord" | "tenant"
): string {
  if (role === "landlord") {
    return [
      `🌿 *Welcome to Gridee, ${name}!*`,
      ``,
      `You're all set as a *Landlord*. Your tenants can now enjoy clean, prepaid solar energy — and you earn a revenue share every time they top up. 🔋`,
      ``,
      `Here's how to get started:`,
      `👉 Type *ADD PROPERTY* to register your first compound and get a Property Code.`,
      `👉 Share that code with your tenants so they can register under your property.`,
      `👉 Type *HELP* anytime to see all your commands.`,
      ``,
      `_Welcome aboard. Let's power Nigeria together. ⚡_`,
    ].join("\n");
  }

  return [
    `🌿 *Welcome to Gridee, ${name}!*`,
    ``,
    `You're all set as a *Tenant*. No more generator wahala — buy solar tokens and power your flat on your own terms. ⚡`,
    ``,
    `Here's how to get started:`,
    `👉 Type *BUY 2000* to purchase ₦2,000 worth of energy tokens.`,
    `👉 Type *BALANCE* anytime to check how much power you have left.`,
    `👉 Type *HELP* to see everything you can do.`,
    ``,
    `_Enjoy the light! 🌟_`,
  ].join("\n");
}

/**
 * Full command reference for landlords.
 * Shown when a landlord sends the HELP command.
 */
export function helpLandlord(): string {
  return [
    `🌿 *Gridee — Landlord Commands*`,
    ``,
    `Here's everything you can do:`,
    ``,
    `🏠 *MY PROPERTIES* — View all your registered compounds`,
    `➕ *ADD PROPERTY* — Register a new compound and get a Property Code`,
    `🔍 *PROPERTY [CODE]* — Details for a specific property`,
    `   _e.g. PROPERTY GRD-LAG-0042_`,
    `👥 *TENANTS [CODE]* — List all tenants under a property`,
    `💰 *EARNINGS* — Your total revenue share across all properties`,
    `💰 *EARNINGS [CODE]* — Earnings for one specific property`,
    `🏦 *WITHDRAW* — Transfer your earnings to your bank account`,
    `❌ *REMOVE TENANT [PHONE]* — Disconnect a tenant (e.g. after they vacate)`,
    `📋 *HELP* — Show this message again`,
    ``,
    `_Questions? We're always here. 🤝_`,
  ].join("\n");
}

/**
 * Full command reference for tenants.
 * Shown when a tenant sends the HELP command.
 */
export function helpTenant(): string {
  return [
    `🌿 *Gridee — Tenant Commands*`,
    ``,
    `Here's everything you can do:`,
    ``,
    `⚡ *BUY [amount]* — Purchase energy tokens in Naira`,
    `   _e.g. BUY 2000 to spend ₦2,000_`,
    `🔋 *BALANCE* — Check your current token balance and hours remaining`,
    `📜 *HISTORY* — See your last 10 top-ups`,
    `🏠 *MY PROPERTY* — Details of the compound you're registered under`,
    `📋 *HELP* — Show this message again`,
    ``,
    `_Tip: Top up before your balance runs low to avoid interruptions. ⚡_`,
  ].join("\n");
}

/**
 * Generic fallback when an unexpected server-side error occurs.
 * Does NOT expose internal error details or stack traces to the user.
 */
export function errorGeneric(): string {
  return [
    `😕 *Something went wrong on our end.*`,
    ``,
    `Please try again in a moment. If the problem keeps happening, type *HELP* to see your options.`,
    ``,
    `_We're sorry for the inconvenience. 🙏_`,
  ].join("\n");
}

/**
 * Sent when a user's multi-step conversation session has timed out in Redis.
 * Reassures them that their account data is safe before prompting a restart.
 */
export function sessionExpired(): string {
  return [
    `⏰ *Your session has timed out.*`,
    ``,
    `No wahala — just send *Hi* or *START* to begin again. If you're already registered, all your data is safe. 😊`,
  ].join("\n");
}

/**
 * Delivers a one-time password to the user for phone number verification.
 * Security note: explicitly instructs the user never to share the code.
 *
 * @param code - The 6-digit OTP generated by the auth service.
 */
export function otpMessage(code: string): string {
  return [
    `🔐 *Your Gridee verification code is: ${code}*`,
    ``,
    `This code is valid for *5 minutes*. Do not share it with anyone — Gridee will never ask for your OTP.`,
    ``,
    `_If you didn't request this, please ignore this message._`,
  ].join("\n");
}

/**
 * Confirms that the user's account has been created successfully.
 * Distinct from welcomeMessage — this is a short confirmation, not an onboarding guide.
 * Role-aware so the next instruction is relevant to what the user should do immediately.
 *
 * @param name - The user's full name as entered during registration.
 * @param role - The user's role on the platform.
 */
export function registrationSuccess(
  name: string,
  role: "landlord" | "tenant"
): string {
  const nextStep =
    role === "landlord"
      ? `Type *ADD PROPERTY* to register your first compound.`
      : `Type *BUY [amount]* to purchase your first energy tokens.`;

  return [
    `✅ *You're registered, ${name}!*`,
    ``,
    `Your Gridee account is ready. ${nextStep}`,
    ``,
    `_Type *HELP* anytime to see all your options._`,
  ].join("\n");
}

/**
 * Sent when a user enters an OTP that does not match or has already been used.
 * Gives them a clear path to recover without making them feel stuck.
 */
export function invalidOTP(): string {
  return [
    `❌ *Incorrect code.*`,
    ``,
    `That OTP doesn't match what we sent. Please check the message and try again.`,
    ``,
    `_Type *RESEND* if you need a new code._`,
  ].join("\n");
}

/**
 * Confirms that a fresh OTP has been dispatched to the user's number.
 * Reminds them of the validity window so they act quickly.
 */
export function resendOTP(): string {
  return [
    `📨 *A new verification code has been sent to your number.*`,
    ``,
    `It's valid for *5 minutes*. Check your messages and enter the code to continue.`,
    ``,
    `_Still not receiving it? Make sure your number is correct or contact support._`,
  ].join("\n");
}

/**
 * Sent to a landlord immediately after a new property is registered.
 * Surfaces the Property Code prominently — this is the key piece of information
 * the landlord needs to share with their tenants.
 *
 * @param code  - The system-generated property code, e.g. "GRD-LAG-0042".
 * @param label - The human-friendly name the landlord gave the property, e.g. "Surulere Block A".
 */
export function propertyRegistered(code: string, label: string): string {
  return [
    `🏠 *Property registered successfully!*`,
    ``,
    `*${label}* is now live on Gridee.`,
    ``,
    `Your Property Code is: *${code}*`,
    ``,
    `Share this code with your tenants — they'll need it to register under your compound.`,
    ``,
    `_Type *MY PROPERTIES* to view all your compounds._`,
  ].join("\n");
}

/**
 * Sent when a user attempts to register but an account already exists
 * for their phone number. Steers them toward the right action instead
 * of leaving them confused.
 */
export function alreadyRegistered(): string {
  return [
    `👋 *You already have a Gridee account.*`,
    ``,
    `No need to register again — you're all set! Type *HELP* to see what you can do.`,
    ``,
    `_If you think something is wrong with your account, please contact support._`,
  ].join("\n");
}

/**
 * The very first message a new user receives after sending any message.
 * Asks them to identify their role before the registration flow begins.
 */
export function rolePrompt(): string {
  return [
    `🌿 *Welcome to Gridee — Prepaid Solar for Everyone. ⚡*`,
    ``,
    `Before we get started, are you a:`,
    ``,
    `*1* — 🏠 Landlord _(register your compound and earn revenue)_`,
    `*2* — 🔋 Tenant _(buy solar tokens for your flat)_`,
    ``,
    `Reply with *1* or *2* to continue.`,
  ].join("\n");
}

/**
 * Sent to a tenant after they choose "Bank Transfer" as their payment method.
 * Contains everything they need to complete the transfer: account details,
 * reference (MUST be included so the backend can match the payment),
 * NGN amount, GRD they will receive, and a countdown before the window expires.
 *
 * @param accountNumber - The virtual account number generated for this transaction.
 * @param bankName      - The bank holding the virtual account, e.g. "Wema Bank".
 * @param reference     - Unique payment reference — tenant MUST use this as narration.
 * @param amountNGN     - The exact NGN amount to transfer.
 * @param expiryMins    - Minutes until the payment window closes (typically 15).
 * @param grdAmount     - The GRD tokens the tenant will receive upon confirmation.
 */
export function paymentInstructionsBankTransfer(
  accountNumber: string,
  bankName: string,
  reference: string,
  amountNGN: number,
  expiryMins: number,
  grdAmount: number
): string {
  const formattedAmount = amountNGN.toLocaleString("en-NG");
  return [
    `🏦 *Bank Transfer Details*`,
    ``,
    `Transfer exactly *₦${formattedAmount}* to:`,
    ``,
    `🏛 *Bank:* ${bankName}`,
    `💳 *Account Number:* ${accountNumber}`,
    `📝 *Reference / Narration:* ${reference}`,
    ``,
    `⚠️ *Important:* You must use the reference above as your transfer narration so we can match your payment.`,
    ``,
    `You will receive *${grdAmount} GRD* once your payment is confirmed.`,
    ``,
    `⏳ This payment window expires in *${expiryMins} minutes*. After that, type *BUY [amount]* to start again.`,
  ].join("\n");
}

/**
 * Sent to a tenant after they choose "Mobile Money" as their payment method.
 * Covers major Nigerian mobile money networks (OPay, PalmPay, Moniepoint, etc.)
 *
 * @param network    - The mobile money network, e.g. "OPay", "PalmPay".
 * @param reference  - Unique payment reference — tenant MUST include this.
 * @param amountNGN  - The exact NGN amount to send.
 */
export function paymentInstructionsMobileMoney(
  network: string,
  reference: string,
  amountNGN: number
): string {
  const formattedAmount = amountNGN.toLocaleString("en-NG");
  return [
    `📱 *Mobile Money Payment*`,
    ``,
    `Send exactly *₦${formattedAmount}* via *${network}* to:`,
    ``,
    `📝 *Reference:* ${reference}`,
    ``,
    `Make sure to include the reference when sending so we can confirm your payment automatically.`,
    ``,
    `_We'll notify you as soon as your tokens are ready. ⚡_`,
  ].join("\n");
}

/**
 * Sent to a tenant after they choose "Crypto" as their payment method.
 * Shows the USDT wallet address and equivalent amount.
 * Wallet address is on its own line for easy long-press copying on mobile.
 *
 * @param walletAddress - The USDT (TRC-20 or ERC-20) wallet address for this transaction.
 * @param amountUSDT    - The USDT equivalent of the NGN purchase amount.
 * @param reference     - Unique reference the tenant should include in the memo/tag if supported.
 */
export function paymentInstructionsCrypto(
  walletAddress: string,
  amountUSDT: number,
  reference: string
): string {
  return [
    `🪙 *Crypto Payment (USDT)*`,
    ``,
    `Send exactly *${amountUSDT} USDT* to this wallet address:`,
    ``,
    `\`${walletAddress}\``,
    ``,
    `📝 *Reference / Memo:* ${reference}`,
    ``,
    `⚠️ *Send USDT only.* Sending any other token to this address may result in permanent loss of funds.`,
    ``,
    `_We'll credit your GRD tokens once the transaction confirms on-chain. ⚡_`,
  ].join("\n");
}

/**
 * Sent immediately after the backend confirms a successful payment webhook.
 * This is the most important message in the entire flow — the user just paid real money.
 * Should be warm, instant, and show all three key numbers: GRD added, new total, kWh.
 *
 * @param grdAmount     - GRD tokens credited in this transaction.
 * @param newBalance    - The tenant's total GRD balance after this top-up.
 * @param kwhEquivalent - Approximate kWh the new balance represents.
 */
export function paymentConfirmed(
  grdAmount: number,
  newBalance: number,
  kwhEquivalent: number
): string {
  return [
    `✅ *Payment confirmed! Your solar is topped up. ⚡*`,
    ``,
    `*+${grdAmount} GRD* has been added to your account.`,
    ``,
    `🔋 *New balance:* ${newBalance} GRD (≈ ${kwhEquivalent} kWh)`,
    ``,
    `_Enjoy the power! Type *BALANCE* anytime to check your remaining energy._`,
  ].join("\n");
}

/**
 * Sent when the 15-minute (or custom) payment window closes without a confirmed transfer.
 * Does not blame the user — gives them a clean path to try again.
 */
export function paymentExpired(): string {
  return [
    `⏰ *Your payment window has expired.*`,
    ``,
    `No payment was received within the time limit. No money has been deducted from your account.`,
    ``,
    `Type *BUY [amount]* to start a new payment whenever you're ready.`,
    ``,
    `_e.g. BUY 2000 to top up with ₦2,000_`,
  ].join("\n");
}

/**
 * Sent when a payment attempt fails for a specific reason from the payment provider.
 * The `reason` string comes from the backend — keep it short and user-friendly before passing it in.
 *
 * @param reason - A brief, human-readable explanation from the payment provider.
 */
export function paymentFailed(reason: string): string {
  return [
    `❌ *Payment unsuccessful.*`,
    ``,
    `Your payment could not be processed. Reason: _${reason}_`,
    ``,
    `No money has been deducted from your account. Type *BUY [amount]* to try again.`,
    ``,
    `_If the problem continues, please contact support._`,
  ].join("\n");
}

/**
 * SMS / USSD fallback confirmation — sent to users who completed a purchase via USSD.
 * MUST stay under 160 characters (single SMS frame).
 * No emoji, no bold, no WhatsApp formatting — plain text only.
 *
 * @param grdAmount  - GRD tokens credited in this transaction.
 * @param newBalance - The tenant's total GRD balance after this top-up.
 */
export function purchaseSMSConfirmation(
  grdAmount: number,
  newBalance: number,
  dialCode: string
): string {
  return `Gridee: +${grdAmount} GRD added. New balance: ${newBalance} GRD. Dial ${dialCode} to check your account.`;
}
